name: Bug report
description: Create a bug report to help us improve this project
title: "[Bug] "
assignees:
  - sn4k3
body:
  - type: markdown
    attributes:
      value: |
        Before filing, please check if the issue already exists (either open or closed) by using the search bar on the [issues page](https://github.com/sn4k3/SpeciesDatabaseApi/issues?q=). If it does, comment there. Even if it's closed, we can reopen it based on your comment.
  - type: textarea
    id: bug_description
    attributes:
      label: Description of the bug
      description: A clear and concise description of what the bug is. Please, enclose a screenshot whenever possible (even when you think the description is clear). What did you expect to happen?
      placeholder: |
        What is the problem?
        What did you expect?
        You paste or drop screenshots here
    validations:
      required: true
  - type: textarea
    id: to_reproduce
    attributes:
      label: How to reproduce
      description: Code to reproduce the behavior
      placeholder: |
        Steps to reproduce the behavior:
        1. Paste the problematic code here
      render: csharp
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        # Overview before submit
        1. Use descriptive and complete title!
        2. Review all information and make sure it's clear and complete.
        3. Note that the information and files posted here will be public.
